/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LogCollectorRouteImport } from './routes/log-collector'
import { Route as DatabaseSearchRouteImport } from './routes/database-search'
import { Route as BackgroundMonitoringRouteImport } from './routes/background-monitoring'
import { Route as AutorunsRouteImport } from './routes/autoruns'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LogCollectorRoute = LogCollectorRouteImport.update({
  id: '/log-collector',
  path: '/log-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseSearchRoute = DatabaseSearchRouteImport.update({
  id: '/database-search',
  path: '/database-search',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundMonitoringRoute = BackgroundMonitoringRouteImport.update({
  id: '/background-monitoring',
  path: '/background-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsRoute = AutorunsRouteImport.update({
  id: '/autoruns',
  path: '/autoruns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/background-monitoring': typeof BackgroundMonitoringRoute
  '/database-search': typeof DatabaseSearchRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/background-monitoring': typeof BackgroundMonitoringRoute
  '/database-search': typeof DatabaseSearchRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/background-monitoring': typeof BackgroundMonitoringRoute
  '/database-search': typeof DatabaseSearchRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autoruns'
    | '/background-monitoring'
    | '/database-search'
    | '/log-collector'
    | '/network'
    | '/settings'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autoruns'
    | '/background-monitoring'
    | '/database-search'
    | '/log-collector'
    | '/network'
    | '/settings'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/autoruns'
    | '/background-monitoring'
    | '/database-search'
    | '/log-collector'
    | '/network'
    | '/settings'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorunsRoute: typeof AutorunsRoute
  BackgroundMonitoringRoute: typeof BackgroundMonitoringRoute
  DatabaseSearchRoute: typeof DatabaseSearchRoute
  LogCollectorRoute: typeof LogCollectorRoute
  NetworkRoute: typeof NetworkRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-collector': {
      id: '/log-collector'
      path: '/log-collector'
      fullPath: '/log-collector'
      preLoaderRoute: typeof LogCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database-search': {
      id: '/database-search'
      path: '/database-search'
      fullPath: '/database-search'
      preLoaderRoute: typeof DatabaseSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-monitoring': {
      id: '/background-monitoring'
      path: '/background-monitoring'
      fullPath: '/background-monitoring'
      preLoaderRoute: typeof BackgroundMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns': {
      id: '/autoruns'
      path: '/autoruns'
      fullPath: '/autoruns'
      preLoaderRoute: typeof AutorunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorunsRoute: AutorunsRoute,
  BackgroundMonitoringRoute: BackgroundMonitoringRoute,
  DatabaseSearchRoute: DatabaseSearchRoute,
  LogCollectorRoute: LogCollectorRoute,
  NetworkRoute: NetworkRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
