/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LogCollectorRouteImport } from './routes/log-collector'
import { Route as AutorunsRouteImport } from './routes/autoruns'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LogCollectorRoute = LogCollectorRouteImport.update({
  id: '/log-collector',
  path: '/log-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsRoute = AutorunsRouteImport.update({
  id: '/autoruns',
  path: '/autoruns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autoruns': typeof AutorunsRoute
  '/log-collector': typeof LogCollectorRoute
  '/network': typeof NetworkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autoruns' | '/log-collector' | '/network' | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autoruns' | '/log-collector' | '/network' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/autoruns'
    | '/log-collector'
    | '/network'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorunsRoute: typeof AutorunsRoute
  LogCollectorRoute: typeof LogCollectorRoute
  NetworkRoute: typeof NetworkRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-collector': {
      id: '/log-collector'
      path: '/log-collector'
      fullPath: '/log-collector'
      preLoaderRoute: typeof LogCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns': {
      id: '/autoruns'
      path: '/autoruns'
      fullPath: '/autoruns'
      preLoaderRoute: typeof AutorunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorunsRoute: AutorunsRoute,
  LogCollectorRoute: LogCollectorRoute,
  NetworkRoute: NetworkRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
