// @ts-nocheck
// auto-generated by tauri-specta — DO NOT EDIT

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async cmdAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("cmd_app_info");
},
async cmdLogFrontend(message: string) : Promise<void> {
    await TAURI_INVOKE("cmd_log_frontend", { message });
},
async cmdNetworkSnapshot() : Promise<Result<NetworkSnapshotPayload, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkKillProcess(pid: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_kill_process", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkSetPolling(control: NetworkPollingControl) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_set_polling", { control }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkClearHistory() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsScan(options: ScanOptions) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_scan", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsGetResult() : Promise<Result<AutorunItem[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_get_result") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsVerifySignatures(paths: string[]) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_verify_signatures", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsDeleteEntry(entryId: number) : Promise<Result<DeleteResult, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_delete_entry", { entryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsCancelScan(taskId: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_cancel_scan", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsCalculateHash(entryId: number) : Promise<Result<AutorunItem, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_calculate_hash", { entryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsBatchCalculateHash(entryIds: number[]) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_batch_calculate_hash", { entryIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsSigcheck(imagePath: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_sigcheck", { imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenExplorer(path: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenRegedit(registryPath: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_regedit", { registryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenServices() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_services") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsExtractIcon(imagePath: string) : Promise<Result<string | null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_extract_icon", { imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsBatchExtractIcons(paths: string[]) : Promise<Result<([string, string | null])[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_batch_extract_icons", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdProcessSnapshot() : Promise<Result<ProcessSnapshot, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_process_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdProcessChain(pid: number) : Promise<Result<ProcessChain, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_process_chain", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Sysmon installation/service status.
 */
async cmdSysmonStatus() : Promise<Result<SysmonStatus, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the Sysmon event channel is available.
 */
async cmdSysmonIsChannelAvailable() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_is_channel_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install Sysmon with the given config.
 */
async cmdSysmonInstall(acceptEula: boolean) : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_install", { acceptEula }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Uninstall Sysmon.
 */
async cmdSysmonUninstall() : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_uninstall") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update Sysmon configuration.
 */
async cmdSysmonUpdateConfig() : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_update_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get existing (historical) events from the Sysmon channel.
 */
async cmdSysmonGetExistingEvents(limit: number, enabledEventIds: number[]) : Promise<Result<SysmonEvent[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_get_existing_events", { limit, enabledEventIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the default event configurations.
 */
async cmdSysmonDefaultEventConfigs() : Promise<Result<EventConfigEntry[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_default_event_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate Sysmon XML config from enabled events list and write to disk.
 */
async cmdSysmonGenerateConfig(enabledEvents: string[]) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_generate_config", { enabledEvents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start real-time Sysmon event subscription.
 * Events are pushed to the frontend via `evt_sysmon_event` Tauri event.
 */
async cmdSysmonStartSubscription(enabledEventIds: number[], pollIntervalMs: number | null) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_start_subscription", { enabledEventIds, pollIntervalMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop real-time Sysmon event subscription.
 */
async cmdSysmonStopSubscription() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_stop_subscription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Sysmon subscription is currently active.
 */
async cmdSysmonIsSubscribing() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_is_subscribing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the Sysmon event log maximum size in MB.
 */
async cmdSysmonGetLogMaxSize() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_get_log_max_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the Sysmon event log maximum size in MB.
 */
async cmdSysmonSetLogMaxSize(sizeMb: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_set_log_max_size", { sizeMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppInfo = { name: string; version: string; build: string; is_admin: boolean }
export type AutorunItem = { id: number; category: string; entry: string; enabled: boolean; location: string; description: string; publisher: string; image_path: string | null; launch_string: string | null; timestamp: string | null; file_exists: boolean; file_size: number | null; file_version: string | null; service_name: string | null; md5: string | null; sha256: string | null; risk: RiskLevel; risk_reasons: string[]; signature: SignatureStatus }
export type ConnState = "CLOSED" | "LISTEN" | "SYN_SENT" | "SYN_RCVD" | "ESTABLISHED" | "FIN_WAIT_1" | "FIN_WAIT_2" | "CLOSE_WAIT" | "CLOSING" | "LAST_ACK" | "TIME_WAIT" | "DELETE_TCB" | "NONE"
export type DeleteResult = { success: boolean; message: string }
/**
 * Event configuration entry.
 */
export type EventConfigEntry = { key: string; name: string; event_id: number; xml_tag: string; default_enabled: boolean }
export type Family = "v4" | "v6"
export type IrError = { kind: "io"; message: string } | { kind: "permission_denied" } | { kind: "external_tool"; message: { tool: string; code: number } } | { kind: "parse"; message: string } | { kind: "network"; message: string } | { kind: "cancelled" } | { kind: "feature_disabled"; message: string } | { kind: "internal"; message: string }
export type NetConn = { proto: Proto; family: Family; local: NetEndpoint; remote: NetEndpoint; state: ConnState; pid: number; process_name: string | null; process_path: string | null; process_cmdline: string | null; first_seen: number; last_seen: number; is_current: boolean }
export type NetEndpoint = { addr: string; port: number }
export type NetworkPollingControl = { interval_ms: number | null; paused: boolean | null; retention: RetentionPolicyDto | null }
export type NetworkSnapshotPayload = { items: NetConn[]; timestamp: number }
/**
 * A chain from a target process up to the root (PID 0 or 4).
 */
export type ProcessChain = { 
/**
 * Ordered [target, parent, grandparent, ..., root].
 */
nodes: ProcessNode[] }
/**
 * A lightweight process entry from a system-wide snapshot.
 */
export type ProcessEntry = { pid: number; ppid: number; name: string; exe: string | null }
/**
 * A single process in a chain, with optional suspicion metadata.
 */
export type ProcessNode = { pid: number; name: string; 
/**
 * Full executable path, if available.
 */
exe: string | null; 
/**
 * Command line, if available.
 */
cmdline: string | null; 
/**
 * Process creation time as formatted string "HH:MM:SS", if available.
 */
create_time: string | null; 
/**
 * Whether this is the target process the chain was requested for.
 */
is_target: boolean; 
/**
 * Whether this process was flagged as suspicious.
 */
is_suspicious: boolean; 
/**
 * Why the process is suspicious, if flagged.
 */
suspicious_reason: string | null }
/**
 * Full process snapshot result.
 */
export type ProcessSnapshot = { processes: ProcessEntry[]; timestamp: number }
export type Proto = "tcp" | "udp"
export type RetentionPolicyDto = "none" | { seconds: number } | "forever"
export type RiskLevel = "safe" | "suspicious" | "high_risk"
export type ScanOptions = { include_hash: boolean; category_filter: string[] | null }
export type SignatureStatus = { kind: "valid"; detail: { signer: string } } | { kind: "invalid"; detail: { message: string } } | { kind: "unsigned" } | { kind: "not_verified" }
/**
 * Unified Sysmon event struct. Fields not applicable to a given event type are None/empty.
 */
export type SysmonEvent = { event_id: number; event_type: SysmonEventType; timestamp: string; timestamp_epoch: number; timestamp_valid: boolean; record_id: number | null; raw_data: { [key in string]: string }; process_id: number; process_name: string; process_path: string; user: string; rule_name: string; query_name: string; query_results: string; query_status: number; source_ip: string; source_port: number; destination_ip: string; destination_port: number; protocol: string; initiated: boolean; is_external: boolean; source_process_id: number; source_process_name: string; source_process_path: string; target_process_id: number; target_process_name: string; target_process_path: string; start_address: string; start_module: string; start_function: string; is_suspicious: boolean; target_filename: string; creation_utc_time: string }
/**
 * Event type discriminator.
 */
export type SysmonEventType = "process_create" | "file_create_time" | "network_connect" | "process_terminate" | "driver_load" | "image_load" | "create_remote_thread" | "raw_access_read" | "process_access" | "file_create" | "registry_event" | "file_create_stream_hash" | "pipe_event" | "wmi_event" | "dns" | "dns_client" | "file_delete" | "clipboard_change" | "process_tampering" | "file_delete_detected" | "unknown"
/**
 * Sysmon service status info.
 */
export type SysmonStatus = { installed: boolean; running: boolean; service_name: string | null; sysmon_exe_exists: boolean; config_exists: boolean; sysmon_exe_path: string; config_path: string; started_by_irtool: boolean; config_managed_by_irtool: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
