// @ts-nocheck
// auto-generated by tauri-specta — DO NOT EDIT

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async cmdAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("cmd_app_info");
},
async cmdLogFrontend(message: string) : Promise<void> {
    await TAURI_INVOKE("cmd_log_frontend", { message });
},
async cmdAppForceQuit() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_app_force_quit") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 自定义重启命令：解决便携版下 tauri-plugin-process 的 relaunch() 因单实例互斥锁
 * 导致新进程启动后立即退出的问题。
 * 
 * 原理：先退出后台模式，再释放所有单实例保护（tauri-plugin-single-instance 的 mutex +
 * 隐藏窗口，以及自定义的 CreateMutexW 互斥锁），再通过 ShellExecuteW 启动新实例。
 * ShellExecuteW 原生使用 UTF-16 编码，完美支持中文/Unicode 路径。
 * 必须在启动新实例前先释放所有单实例保护，否则新进程检测到已有实例会直接退出。
 */
async cmdRelaunch() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_relaunch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkSnapshot() : Promise<Result<NetworkSnapshotPayload, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkKillProcess(pid: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_kill_process", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkSetPolling(control: NetworkPollingControl) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_set_polling", { control }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkClearHistory() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkRefreshCmdline(pid: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_refresh_cmdline", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsScan(options: ScanOptions) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_scan", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsGetResult() : Promise<Result<AutorunItem[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_get_result") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsVerifySignatures(paths: string[]) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_verify_signatures", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsDeleteEntry(entryId: number) : Promise<Result<DeleteResult, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_delete_entry", { entryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsCancelScan(taskId: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_cancel_scan", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsCalculateHash(entryId: number) : Promise<Result<AutorunItem, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_calculate_hash", { entryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsBatchCalculateHash(entryIds: number[]) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_batch_calculate_hash", { entryIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsSigcheck(imagePath: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_sigcheck", { imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenExplorer(path: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_explorer", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenRegedit(registryPath: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_regedit", { registryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsOpenServices() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_open_services") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsExtractIcon(imagePath: string) : Promise<Result<string | null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_extract_icon", { imagePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsBatchExtractIcons(paths: string[]) : Promise<Result<([string, string | null])[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_batch_extract_icons", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsIsScanning() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_is_scanning") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdProcessSnapshot() : Promise<Result<ProcessSnapshot, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_process_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdProcessChain(pid: number) : Promise<Result<ProcessChain, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_process_chain", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNetworkQueryByPid(pid: number) : Promise<Result<NetConn[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_network_query_by_pid", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAutorunsQueryByPath(exePath: string) : Promise<Result<AutorunItem[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_autoruns_query_by_path", { exePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonStatus() : Promise<Result<SysmonStatus, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonIsChannelAvailable() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_is_channel_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonInstall(acceptEula: boolean) : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_install", { acceptEula }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonUninstall() : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_uninstall") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonUpdateConfig() : Promise<Result<[boolean, string], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_update_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonGetExistingEvents(limit: number, enabledEventIds: number[]) : Promise<Result<SysmonEvent[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_get_existing_events", { limit, enabledEventIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonDefaultEventConfigs() : Promise<Result<EventConfigEntry[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_default_event_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonGenerateConfig(enabledEvents: string[]) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_generate_config", { enabledEvents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonStartSubscription(enabledEventIds: number[], pollIntervalMs: number | null) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_start_subscription", { enabledEventIds, pollIntervalMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonStopSubscription() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_stop_subscription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonIsSubscribing() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_is_subscribing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonGetEventCount(enabledEventIds: number[]) : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_get_event_count", { enabledEventIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonGetLogMaxSize() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_get_log_max_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSysmonSetLogMaxSize(sizeMb: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_sysmon_set_log_max_size", { sizeMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetConfig() : Promise<Result<MonitorConfig, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorUpdateConfig(config: MonitorConfig) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_update_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorEnterBackground() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_enter_background") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorExitBackground() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_exit_background") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetAlerts(limit: number) : Promise<Result<Alert[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_alerts", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorIsBackground() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_is_background") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorClearAlerts() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_clear_alerts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetEvents(limit: number) : Promise<Result<MonitorEvent[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_events", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetEventCount() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_event_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorSearchEvents(source: string | null, eventType: string | null, processName: string | null, keyField: string | null, searchText: string | null, limit: number, offset: number) : Promise<Result<MonitorEvent[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_search_events", { source, eventType, processName, keyField, searchText, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorSearchEventPage(query: EventQuery) : Promise<Result<EventPage, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_search_event_page", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetTelemetry() : Promise<Result<RuntimeTelemetry, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_telemetry") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorTestFeishu(webhookUrl: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_test_feishu", { webhookUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorClearEvents() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_clear_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorEventTypeCounts() : Promise<Result<([string, number])[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_event_type_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMonitorGetDbSize() : Promise<Result<number, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_monitor_get_db_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdWorkspaceRunCommand(program: string, args: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_workspace_run_command", { program, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdWorkspaceUnhidePath(path: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_workspace_unhide_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdWorkspaceTakeOwnership(path: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_workspace_take_ownership", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdWorkspaceSamplePath(path: string, outputDir: string, password: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_workspace_sample_path", { path, outputDir, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdWorkspaceOpenPath(path: string) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_workspace_open_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapIsAvailable() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_is_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapStart(config: PcapConfig) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_start", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapStop() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapIsRunning() : Promise<Result<boolean, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_is_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapListAdapters() : Promise<Result<AdapterInfo[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_list_adapters") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPcapGetCounters() : Promise<Result<PcapCountersSnapshot, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_pcap_get_counters") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdShowAlertPopup(params: AlertPopupParams) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_show_alert_popup", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdToolsCheck() : Promise<Result<ToolStatus[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_tools_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdToolsDownload(toolIds: string[]) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_tools_download", { toolIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdToolsImportZip(toolId: string, zipPath: string) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_tools_import_zip", { toolId, zipPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsListProfiles() : Promise<Result<BrowserProfile[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_list_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsScanExtensions(browser: BrowserKind, profileName: string) : Promise<Result<ExtensionInventory, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_scan_extensions", { browser, profileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsScanAllExtensions(browser: BrowserKind) : Promise<Result<ExtensionInventory[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_scan_all_extensions", { browser }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsScanDownloads(browser: BrowserKind, profileName: string) : Promise<Result<DownloadAttribution, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_scan_downloads", { browser, profileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsRecoverTabs(browser: BrowserKind, profileName: string) : Promise<Result<SessionRecoveryResult, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_recover_tabs", { browser, profileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsAttributeHistory(browser: BrowserKind, profileName: string, targetTime: string) : Promise<Result<HistoryAttribution, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_attribute_history", { browser, profileName, targetTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsScanHistory(browser: BrowserKind, profileName: string, limit: number | null, since: number | null) : Promise<Result<HistoryList, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_scan_history", { browser, profileName, limit, since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsContextAttribution(domain: string, ip: string | null, processName: string, pid: number, timestamp: string, cmdline: string | null) : Promise<Result<EvidenceObject, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_context_attribution", { domain, ip, processName, pid, timestamp, cmdline }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdBrowserForensicsAttributeExtension(processName: string, pid: number, domain: string, cmdline: string | null) : Promise<Result<ExtensionAttribution, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_attribute_extension", { processName, pid, domain, cmdline }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 注册 Helper Extension 的 Native Messaging Host
 * 
 * 写入 Native Messaging Host JSON 配置文件并注册到浏览器注册表。
 * 支持 Chrome / Edge。
 * 
 * 扩展 ID 默认由 manifest.json 的 `key` 字段固定，无需前端传入。
 * `extension_id_override` 用于兜底场景（高级选项），用户可手动输入扩展 ID 覆盖。
 */
async cmdBrowserForensicsInstallNativeMessagingHost(browser: BrowserKind, extensionIdOverride: string | null) : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_install_native_messaging_host", { browser, extensionIdOverride }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取 Helper Extension 目录的绝对路径。
 * 
 * dev 模式：返回 workspace 根下的 `helper-extension/` 目录（基于 CARGO_MANIFEST_DIR 解析）。
 * release 模式：返回 Tauri resource_dir 下的 `helper-extension/`。
 * 
 * 前端用此路径：1) 复制到剪贴板供用户 Load unpacked 时粘贴；2) 判断扩展目录是否存在。
 */
async cmdBrowserForensicsGetHelperExtensionPath() : Promise<Result<string, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_get_helper_extension_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 打开浏览器的扩展管理页。
 * 
 * Chrome → `chrome://extensions`
 * Edge   → `edge://extensions`
 * 
 * 通过启动浏览器 exe 并传递 URL 参数实现（`chrome://` 不是标准 URL scheme，
 * 无法用 shell open 直接打开）。浏览器 exe 路径从注册表或 Program Files 查找。
 */
async cmdBrowserForensicsOpenExtensionsPage(browser: BrowserKind) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_open_extensions_page", { browser }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 基于域名/IP 的归因：查找所有与目标相关的浏览器痕迹
 */
async cmdBrowserForensicsAttributeByDomain(target: string, browser: BrowserKind) : Promise<Result<DomainAttribution[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_attribute_by_domain", { target, browser }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 向 Helper Extension 下发域名过滤规则（config 下行通道）。
 * 
 * 写入 `%TEMP%\irtool\config.json`，NMH host 检测到文件变更后
 * 通过 stdout 向扩展转发 `{"type":"config","filterDomains":[...]}`。
 * 
 * 传递空数组可清除过滤规则。
 */
async cmdBrowserForensicsSendConfig(filterDomains: string[]) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_send_config", { filterDomains }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取当前已下发的 filterDomains（用于 UI 启动时同步显示）。
 * 
 * 从 `%TEMP%\irtool\config.json` 读取。文件不存在时返回空数组。
 * 用途：IRtool 重启后 UI store 清空，但磁盘 config 仍有效，扩展继续按旧配置过滤；
 * 此命令让 UI 能把磁盘上的已下发域名同步回界面，避免"已下发但 UI 看不到"的不一致。
 */
async cmdBrowserForensicsGetConfig() : Promise<Result<string[], IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 下发自我卸载信号给扩展（手动清理）。
 *
 * 在 config.json 中写入 `selfUninstall: <timestamp>`，NMH 检测到 mtime 变化后
 * 透传给扩展，扩展调用 `chrome.management.uninstallSelf()` 立即卸载。
 *
 * 用途：应急响应场景，用户点击"清理扩展"按钮时调用。
 * 注意：此操作不可逆，扩展会被立即卸载。
 */
async cmdBrowserForensicsSelfUninstall() : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_self_uninstall") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置扩展自我清理超时时间（分钟）。
 *
 * 写入 config.json 的 `selfCleanupTimeoutMin` 字段：
 * - 0 = 禁用自动清理
 * - >0 = 启用，IRtool 离线超过该时长后扩展自动卸载（默认 60）
 */
async cmdBrowserForensicsSetSelfCleanupTimeout(timeoutMin: number) : Promise<Result<null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_set_self_cleanup_timeout", { timeoutMin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取当前 selfCleanupTimeoutMin 配置。
 *
 * 返回 None 时 UI 应显示默认值 60。
 */
async cmdBrowserForensicsGetSelfCleanupTimeout() : Promise<Result<number | null, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_get_self_cleanup_timeout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 查询 Helper Extension 连接状态
 */
async cmdBrowserForensicsExtensionStatus() : Promise<Result<ExtensionConnectionStatus, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_extension_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重新连接 Helper Extension
 * 
 * 1. kill 所有卡死的 NMH 进程（irtool-native-messaging-host.exe）
 * 2. 下发 reconnectSignal 给扩展（通过 config.json → NMH → 扩展）
 * 扩展收到后立即重置退避计数器并尝试重连，省去等待指数退避的时间
 * 3. 返回诊断信息（NMH 二进制路径/存在性、连接状态）
 * 
 * 注意：reconnectSignal 只有在 NMH 进程存活且扩展 port 已断开时才有效。
 * 如果 NMH 进程被 kill，扩展的 onDisconnect 会触发自动重连（无需 signal）。
 */
async cmdBrowserForensicsReconnectExtension() : Promise<Result<ReconnectDiagnostics, IrError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_browser_forensics_reconnect_extension") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 适配器信息
 */
export type AdapterInfo = { name: string; ip: string; description: string }
/**
 * 告警记录
 */
export type Alert = { id: number; timestamp: number; rule_name: string; event_type: string; process_name: string; key_field: string; action_taken: string; raw_json: string }
export type AlertPopupParams = { rule_name: string; key_field: string; event_type: string; process_name: string; protocol: string; timestamp: number; source_addr: string | null; remote_addr: string | null; process_chain: string | null }
export type AppInfo = { name: string; version: string; is_admin: boolean }
/**
 * 证据置信度等级
 * 
 * - Confirmed: P1 Helper / P2 CDP 铁证
 * - Probable: P0 高分关联（total >= 70）
 * - Possible: P0 低分关联（total < 70）
 */
export type AttributionLevel = "confirmed" | "probable" | "possible"
export type AutorunItem = { id: number; category: string; entry: string; enabled: boolean; location: string; description: string; publisher: string; image_path: string | null; launch_string: string | null; timestamp: string | null; file_exists: boolean; file_size: number | null; file_version: string | null; service_name: string | null; md5: string | null; sha256: string | null; risk: RiskLevel; risk_reasons: string[]; signature: SignatureStatus }
/**
 * Chromium 系浏览器类型
 */
export type BrowserKind = "chrome" | "edge"
/**
 * 浏览器 Profile 信息
 */
export type BrowserProfile = { browser: BrowserKind; 
/**
 * Profile 目录名（如 "Default", "Profile 1"）
 */
name: string; 
/**
 * Profile 显示名（来自 Local State 文件，可能为 None）
 */
display_name: string | null; 
/**
 * Profile 目录完整路径
 */
path: string }
export type CmdlineStatus = "unknown" | "pending" | "ready" | "denied" | "exited" | "failed"
export type ConnState = "CLOSED" | "LISTEN" | "SYN_SENT" | "SYN_RCVD" | "ESTABLISHED" | "FIN_WAIT_1" | "FIN_WAIT_2" | "CLOSE_WAIT" | "CLOSING" | "LAST_ACK" | "TIME_WAIT" | "DELETE_TCB" | "NONE"
/**
 * 当前标签页（Session Recovery 的占位结构，Phase 3 实现后填充）
 */
export type CurrentTab = { url: string; title: string; active: boolean; evidence_type: string }
/**
 * Chrome 对下载文件的安全判定值
 */
export type DangerType = "NOT_DANGEROUS" | "DANGEROUS_URL" | "DANGEROUS_CONTENT" | "DANGEROUS_HOST" | "UNCOMMON_URL" | "POTENTIALLY_UNWANTED" | "ALLOWLISTED_BY_POLICY" | "UNKNOWN"
export type DeleteResult = { success: boolean; message: string }
/**
 * 基于域名的归因结果
 */
export type DomainAttribution = { 
/**
 * 目标域名/IP
 */
target: string; 
/**
 * 浏览器类型
 */
browser: BrowserKind; 
/**
 * Profile 名
 */
profile: string; 
/**
 * 匹配的扩展（权限覆盖目标域名）
 */
matching_extensions: MatchedExtension[]; 
/**
 * 访问过目标域名的浏览记录
 */
related_history: HistoryEntry[]; 
/**
 * 从目标域名下载的文件
 */
related_downloads: DownloadInfo[]; 
/**
 * 包含目标域名的当前标签页
 */
related_tabs: CurrentTab[] }
/**
 * 下载溯源结果
 */
export type DownloadAttribution = { browser: BrowserKind; profile: string; downloads: DownloadInfo[] }
/**
 * 单个下载记录
 */
export type DownloadInfo = { 
/**
 * 下载文件名
 */
filename: string; 
/**
 * 下载文件本地路径
 */
local_path: string; 
/**
 * 下载源 URL
 */
download_url: string; 
/**
 * 来源页面 URL
 */
referrer: string | null; 
/**
 * 下载开始时间
 */
start_time: string | null; 
/**
 * 下载完成时间
 */
end_time: string | null; 
/**
 * 文件大小（字节）
 */
total_bytes: number | null; 
/**
 * Chrome 安全判定
 */
danger_type: DangerType; 
/**
 * 用户是否打开了文件
 */
opened: boolean; 
/**
 * 中断原因
 */
interrupt_reason: string | null; 
/**
 * 证据类型
 */
evidence_type: string; 
/**
 * 完整重定向链（按 chain_index ASC 排序）
 */
url_chain: string[]; 
/**
 * 发起下载的标签页 URL（新版 schema 字段）
 */
tab_url: string | null; 
/**
 * 标签页 referrer（新版 schema 字段）
 */
tab_referrer_url: string | null }
/**
 * Event configuration entry.
 */
export type EventConfigEntry = { key: string; name: string; event_id: number; xml_tag: string; default_enabled: boolean }
/**
 * 事件分页结果
 */
export type EventPage = { items: MonitorEvent[]; total: number; limit: number; offset: number }
/**
 * 事件分页查询参数
 */
export type EventQuery = { source: string | null; event_type: string | null; process_name: string | null; key_field: string | null; is_external: boolean | null; search_text: string | null; limit: number; offset: number }
export type EventSource = "sysmon" | "dns_client" | "net_monitor" | "pcap"
/**
 * 统一证据对象（设计方案目标 JSON 结构的 Rust 对应）
 * 
 * `attribute_browser_context` 的返回值，组合 5 类子证据并通过 `overall_score`/`overall_confidence`
 * 给出综合归因结论。P0 阶段 `alert_id`/`tab_attribution` 暂为 None。
 */
export type EvidenceObject = { domain: string; process: string; pid: number; alert_id: string | null; malicious_connection: MaliciousConnection; history_correlation: HistoryCorrelation | null; downloads: DownloadInfo[]; navigation_chain: NavChainNode[]; extension_attribution: ExtensionAttributionSummary | null; tab_attribution: TabAttribution | null; overall_confidence: AttributionLevel; overall_score: number }
/**
 * 证据评分（P0.2 填充评分逻辑，P0.1 仅定义结构）
 */
export type EvidenceScore = { time_score: number; domain_score: number; chain_score: number; 
/**
 * ≤ 100
 */
total: number }
/**
 * 扩展归因 Layer 1 结果
 */
export type ExtensionAttribution = { 
/**
 * 归因标签
 */
label: string; 
/**
 * 浏览器类型
 */
browser: BrowserKind; 
/**
 * Profile 名
 */
profile: string; 
/**
 * 进程 PID
 */
pid: number; 
/**
 * 目标域名
 */
domain: string; 
/**
 * 候选扩展列表（权限匹配结果）
 */
candidate_extensions: MatchedExtension[] }
/**
 * 扩展归因汇总（P0 阶段 Probable/Possible，P1 可达 Confirmed）
 */
export type ExtensionAttributionSummary = { confidence: AttributionLevel; matched: MatchedExtension[] }
/**
 * 扩展连接状态快照
 */
export type ExtensionConnectionStatus = { connected: boolean; last_heartbeat_ms: number; last_event_ms: number }
/**
 * 单个扩展的完整信息
 */
export type ExtensionInfo = { id: string; name: string; version: string; description: string | null; enabled: boolean; install_time: string | null; install_source: string | null; update_url: string | null; was_installed_by_default: boolean | null; permissions: string[]; host_permissions: string[]; has_content_scripts: boolean; has_background: boolean; preferences_tampered: boolean; risk_flags: string[]; ioc_matches: IocMatch[]; path: string; risk_score: number; risk_level: RiskLevel }
/**
 * 扩展资产清单
 */
export type ExtensionInventory = { browser: BrowserKind; profile: string; extensions: ExtensionInfo[] }
export type Family = "v4" | "v6"
/**
 * History 关联结果
 */
export type HistoryAttribution = { browser: BrowserKind; profile: string; recent_browser_activity: RecentActivity[]; navigation_chain: NavChainNode[] }
/**
 * 历史关联详情（含评分）
 */
export type HistoryCorrelation = { confidence: AttributionLevel; score: EvidenceScore; recent_activity: ScoredActivity[] }
/**
 * 历史记录条目（用于 scan_history 返回）
 */
export type HistoryEntry = { url: string; title: string; visit_time: string; visit_count: number }
/**
 * History 列表结果
 */
export type HistoryList = { browser: BrowserKind; profile: string; entries: HistoryEntry[] }
/**
 * IOC 匹配结果
 */
export type IocMatch = { ioc_type: string; value: string; severity: string }
export type IrError = { kind: "io"; message: string } | { kind: "permission_denied" } | { kind: "external_tool"; message: { tool: string; code: number } } | { kind: "parse"; message: string } | { kind: "network"; message: string } | { kind: "cancelled" } | { kind: "feature_disabled"; message: string } | { kind: "internal"; message: string }
/**
 * 恶意连接信息
 */
export type MaliciousConnection = { domain: string; ip: string | null; process: string; pid: number; browser: BrowserKind; profile: string; timestamp: string }
/**
 * 匹配到的扩展
 */
export type MatchedExtension = { id: string; name: string; version: string; risk_flags: string[]; 
/**
 * 匹配到的 host_permissions 模式
 */
matched_patterns: string[]; 
/**
 * 是否拥有敏感权限组合（如 webRequest）
 */
has_sensitive_permissions: boolean }
/**
 * 后台监控配置
 */
export type MonitorConfig = { 
/**
 * 是否启用后台监控模式
 */
background_mode: boolean; 
/**
 * 后台模式时持久化哪些事件类型，空=全部
 */
persist_event_types: string[]; 
/**
 * SQLite 中事件保留天数，0=永久
 */
retention_days: number; 
/**
 * 监控规则列表
 */
rules: MonitorRule[]; 
/**
 * 数据库存储路径，空=使用默认路径（可执行文件同目录/data/monitor.db）
 */
db_path: string; 
/**
 * 启用 TLS SNI 提取（网络层抓包 TCP:443）
 */
enable_sni?: boolean; 
/**
 * 启用网络层 DNS 抓包（UDP:53）
 */
enable_dns_pcap?: boolean; 
/**
 * 指定绑定的适配器 IP，None = 自动检测
 */
adapter_ip?: string | null; 
/**
 * 抓包自动停止时长（秒），0 = 不限制
 */
max_duration_secs?: number; 
/**
 * 每次从数据库加载多少条记录（供前端review使用）
 */
load_limit: number; 
/**
 * 数据库最大大小（MB），0=不限制
 */
max_size_mb?: number; 
/**
 * 命令行富化模式（0=关闭，1=后台）
 */
cmdline_enrich?: number; 
/**
 * 通知配置（与告警规则分离）
 */
notify_config?: NotifyConfig }
/**
 * 生成唯一 ID（基于时间戳和名称哈希）
 */
export type MonitorEvent = { 
/**
 * 数据库记录 ID（由 SQLite 自动生成），仅查询 DB 时有值，采集时始终为 0
 */
id: number; 
/**
 * epoch 毫秒
 */
timestamp: number; 
/**
 * 事件来源
 */
source: EventSource; 
/**
 * 事件类型标识（dns / dns_client / network_connect / ...）
 */
event_type: string; 
/**
 * 进程名
 */
process_name: string; 
/**
 * 规则匹配关键字段：域名 or IP:Port
 */
key_field: string; 
/**
 * 原始数据 JSON
 */
raw_json: string }
/**
 * 监控规则
 */
export type MonitorRule = { 
/**
 * 规则唯一 ID（用于关联通知配置）
 */
id: string; name: string; 
/**
 * 匹配目标：域名（支持 *.suffix 通配）or IP or CIDR
 */
targets: string[]; 
/**
 * 只匹配哪些事件类型，空=全部
 */
event_types: string[]; 
/**
 * 是否启用
 */
enabled: boolean }
/**
 * Navigation Chain 节点
 */
export type NavChainNode = { url: string; title: string | null; transition: string | null; 
/**
 * 高位限定符字符串列表（如 "ClientRedirect"、"ServerRedirect"）
 */
qualifiers: string[]; 
/**
 * visits.referrer 的 visit id 字符串形式（P0.3 阶段不 JOIN urls 表）
 */
referrer: string | null }
export type NetConn = { proto: Proto; family: Family; local: NetEndpoint; remote: NetEndpoint; state: ConnState; pid: number; process_name: string | null; process_path: string | null; process_cmdline: string | null; cmdline_status: CmdlineStatus; first_seen: number; last_seen: number; is_current: boolean }
export type NetEndpoint = { addr: string; port: number }
export type NetworkPollingControl = { interval_ms: number | null; paused: boolean | null; retention: RetentionPolicyDto | null }
export type NetworkSnapshotPayload = { items: NetConn[]; timestamp: number }
/**
 * 通知配置（与告警规则分离）
 */
export type NotifyConfig = { 
/**
 * 触发弹窗的规则 ID 列表
 */
popup_rule_ids: string[]; 
/**
 * 触发飞书的规则 ID 列表
 */
feishu_rule_ids: string[]; 
/**
 * 飞书 Webhook URL
 */
feishu_webhook_url: string; 
/**
 * 弹窗显示时长（秒），0 = 不自动关闭
 */
popup_duration_secs?: number }
/**
 * pcap 配置
 */
export type PcapConfig = { enable_sni: boolean; enable_dns_pcap: boolean; 
/**
 * Optional specific adapter IP to bind to. None = auto-detect.
 */
adapter_ip: string | null; 
/**
 * Auto-stop after this many seconds. 0 = no limit.
 */
max_duration_secs?: number }
/**
 * 捕获计数器快照
 */
export type PcapCountersSnapshot = { packets_seen: number; events_extracted: number; parse_errors: number; dropped_events: number }
/**
 * A chain from a target process up to the root (PID 0 or 4).
 */
export type ProcessChain = { 
/**
 * Ordered [target, parent, grandparent, ..., root].
 */
nodes: ProcessNode[] }
/**
 * A lightweight process entry from a system-wide snapshot.
 */
export type ProcessEntry = { pid: number; ppid: number; name: string; exe: string | null; is_suspicious: boolean; suspicious_reason: string | null }
/**
 * A single process in a chain, with optional suspicion metadata.
 */
export type ProcessNode = { pid: number; name: string; 
/**
 * Full executable path, if available.
 */
exe: string | null; 
/**
 * Command line, if available.
 */
cmdline: string | null; 
/**
 * Process creation time as formatted string "HH:MM:SS", if available.
 */
create_time: string | null; 
/**
 * Whether this is the target process the chain was requested for.
 */
is_target: boolean; 
/**
 * Whether this process was flagged as suspicious.
 */
is_suspicious: boolean; 
/**
 * Why the process is suspicious, if flagged.
 */
suspicious_reason: string | null }
/**
 * Full process snapshot result.
 */
export type ProcessSnapshot = { processes: ProcessEntry[]; timestamp: number }
export type Proto = "tcp" | "udp"
/**
 * 近期浏览器活动记录
 */
export type RecentActivity = { url: string; title: string; visit_time: string; tier: TimeTier; time_distance_ms: number; evidence_type: string; score: EvidenceScore | null }
/**
 * 重新连接诊断结果
 */
export type ReconnectDiagnostics = { 
/**
 * 被 kill 的 NMH 进程数
 */
killed_processes: number; 
/**
 * NMH 二进制路径（从 install_helper 推算）
 */
nmh_exe_path: string; 
/**
 * NMH 二进制是否存在
 */
nmh_exe_exists: boolean; 
/**
 * 当前连接状态
 */
connection: ExtensionConnectionStatus }
/**
 * 恢复的标签页
 */
export type RecoveredTab = { url: string; title: string; active: boolean; tab_index: number | null }
export type RetentionPolicyDto = "none" | { seconds: number } | "forever"
export type RiskLevel = "safe" | "suspicious" | "high_risk"
/**
 * 扩展风险等级
 */
export type RiskLevel = "Low" | "Medium" | "High"
/**
 * 运行模式
 */
export type RuntimeMode = "Foreground" | "Background"
/**
 * 运行时遥测信息
 */
export type RuntimeTelemetry = { mode: RuntimeMode; started_at: number | null; events_written: number; events_dropped: number; last_event_at: number | null; last_error: string | null }
export type ScanOptions = { include_hash: boolean; category_filter: string[] | null }
/**
 * 评分后的历史活动条目
 */
export type ScoredActivity = { activity: RecentActivity; score: EvidenceScore }
/**
 * Session Recovery 结果
 */
export type SessionRecoveryResult = { browser: BrowserKind; profile: string; tabs: RecoveredTab[]; parse_errors: string[] }
export type SignatureStatus = { kind: "valid"; detail: { signer: string } } | { kind: "invalid"; detail: { message: string } } | { kind: "unsigned" } | { kind: "not_verified" }
/**
 * Unified Sysmon event struct. Fields not applicable to a given event type are None/empty.
 */
export type SysmonEvent = { event_id: number; event_type: SysmonEventType; timestamp: string; timestamp_epoch: number; timestamp_valid: boolean; record_id: number | null; raw_data: { [key in string]: string }; process_id: number; process_name: string; process_path: string; user: string; rule_name: string; query_name: string; query_results: string; query_status: number; source_ip: string; source_port: number; destination_ip: string; destination_port: number; protocol: string; initiated: boolean; is_external: boolean; source_process_id: number; source_process_name: string; source_process_path: string; target_process_id: number; target_process_name: string; target_process_path: string; start_address: string; start_module: string; start_function: string; is_suspicious: boolean; target_filename: string; creation_utc_time: string }
/**
 * Event type discriminator.
 */
export type SysmonEventType = "process_create" | "file_create_time" | "network_connect" | "process_terminate" | "driver_load" | "image_load" | "create_remote_thread" | "raw_access_read" | "process_access" | "file_create" | "registry_event" | "file_create_stream_hash" | "pipe_event" | "wmi_event" | "dns" | "dns_client" | "dns_pcap" | "tls_sni" | "file_delete" | "clipboard_change" | "process_tampering" | "file_delete_detected" | "unknown"
/**
 * Sysmon service status info.
 */
export type SysmonStatus = { installed: boolean; running: boolean; service_name: string | null; sysmon_exe_exists: boolean; config_exists: boolean; sysmon_exe_path: string; config_path: string; started_by_irtool: boolean; config_managed_by_irtool: boolean }
/**
 * Tab 归因（P2 阶段填充，P0 为 None）
 */
export type TabAttribution = { confidence: AttributionLevel; url: string }
/**
 * 时间窗层级
 */
export type TimeTier = 
/**
 * ±5s，极高概率关联
 */
"immediate" | 
/**
 * ±15s，较高概率关联
 */
"nearby" | 
/**
 * ±30s，参考性关联
 */
"recent"
/**
 * Status of a single tool
 */
export type ToolStatus = { id: string; installed: boolean; version: string | null; files: string[]; missing_files: string[]; optional: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
