mod logger;
mod single_instance;
#[allow(dead_code)]
mod types;

use serde::Serialize;
use specta::Type;
use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};
use tracing::info;

#[derive(Serialize, Type)]
pub struct AppInfo {
    pub name: String,
    pub version: String,
    pub build: String,
    pub is_admin: bool,
}

#[tauri::command]
#[specta::specta]
fn cmd_app_info() -> AppInfo {
    AppInfo {
        name: "IRtool".into(),
        version: env!("CARGO_PKG_VERSION").into(),
        build: "alpha".into(),
        is_admin: is_running_as_admin(),
    }
}

#[cfg(windows)]
fn is_running_as_admin() -> bool {
    use windows::Win32::Foundation::HANDLE;
    use windows::Win32::Security::{GetTokenInformation, TokenElevation, TOKEN_ELEVATION, TOKEN_QUERY};
    use windows::Win32::System::Threading::{GetCurrentProcess, OpenProcessToken};

    unsafe {
        let mut token: HANDLE = HANDLE::default();
        if OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &mut token).is_err() {
            return false;
        }
        let mut elevation = TOKEN_ELEVATION::default();
        let mut size = 0u32;
        GetTokenInformation(
            token,
            TokenElevation,
            Some(&mut elevation as *mut _ as *mut _),
            std::mem::size_of::<TOKEN_ELEVATION>() as u32,
            &mut size,
        )
        .is_ok()
            && elevation.TokenIsElevated != 0
    }
}

#[cfg(not(windows))]
fn is_running_as_admin() -> bool {
    false
}

pub fn run() {
    let log_dir = if cfg!(debug_assertions) {
        std::env::current_dir()
            .unwrap_or_else(|_| std::path::PathBuf::from("."))
            .join("logs")
    } else {
        let local = std::env::var_os("LOCALAPPDATA")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|| std::path::PathBuf::from("."));
        local.join("IRtool").join("logs")
    };

    let _logger_guard = logger::init_logger(log_dir.clone());

    info!("============================================");
    info!("IRtool v{} starting", env!("CARGO_PKG_VERSION"));
    info!("Log dir: {}", log_dir.display());
    info!("Admin: {}", is_running_as_admin());
    info!("============================================");

    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![cmd_app_info]);

    #[cfg(debug_assertions)]
    {
        builder
            .export(
                Typescript::default()
                    .header("// @ts-nocheck\n// auto-generated by tauri-specta — DO NOT EDIT\n"),
                concat!(env!("CARGO_MANIFEST_DIR"), "/../../ui/src/lib/bindings.ts"),
            )
            .expect("failed to export bindings.ts");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, args, cwd| {
            single_instance::handle_second_instance(app, args, cwd);
        }))
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            info!("main window setup");
            #[cfg(debug_assertions)]
            {
                let window = app.get_webview_window("main").unwrap();
                window.open_devtools();
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
