import { commands, type IrError } from "@/lib/bindings";
import { invoke } from "@tauri-apps/api/core";
import type { SysmonEvent, SysmonStatus, EventConfigEntry, MonitorEvent, EventPage } from "./types";

// Monitor types (will be auto-generated by specta in debug builds)
interface MonitorConfig {
  background_mode: boolean;
  persist_event_types: string[];
  retention_days: number;
  rules: MonitorRule[];
  db_path: string;
  enable_sni: boolean;
  enable_dns_pcap: boolean;
  adapter_ip: string | null;
  max_duration_secs: number;
  load_limit: number;
}

interface MonitorRule {
  name: string;
  targets: string[];
  event_types: string[];
  actions: NotifyAction[];
  enabled: boolean;
}

type NotifyAction = "popup" | { feishu: { webhook_url: string } };

interface Alert {
  id: number;
  timestamp: number;
  rule_name: string;
  event_type: string;
  process_name: string;
  key_field: string;
  action_taken: string;
  raw_json: string;
}

function unwrap<T>(result: { status: "ok"; data: T } | { status: "error"; error: IrError }): T {
  if (result.status === "error") throw result.error;
  return result.data;
}

export async function getStatus(): Promise<SysmonStatus> {
  return unwrap(await commands.cmdSysmonStatus());
}

export async function isChannelAvailable(): Promise<boolean> {
  return unwrap(await commands.cmdSysmonIsChannelAvailable());
}

export async function install(acceptEula: boolean): Promise<[boolean, string]> {
  return unwrap(await commands.cmdSysmonInstall(acceptEula));
}

export async function uninstall(): Promise<[boolean, string]> {
  return unwrap(await commands.cmdSysmonUninstall());
}

export async function updateConfig(): Promise<[boolean, string]> {
  return unwrap(await commands.cmdSysmonUpdateConfig());
}

export async function getExistingEvents(limit: number, enabledEventIds: number[]): Promise<SysmonEvent[]> {
  return unwrap(await commands.cmdSysmonGetExistingEvents(limit, enabledEventIds));
}

export async function getDefaultEventConfigs(): Promise<EventConfigEntry[]> {
  return unwrap(await commands.cmdSysmonDefaultEventConfigs());
}

export async function generateConfig(enabledEvents: string[]): Promise<string> {
  return unwrap(await commands.cmdSysmonGenerateConfig(enabledEvents));
}

// New commands not yet in bindings — use invoke directly
export async function startSubscription(enabledEventIds: number[], pollIntervalMs?: number): Promise<void> {
  await invoke("cmd_sysmon_start_subscription", {
    enabledEventIds,
    pollIntervalMs: pollIntervalMs ?? null,
  });
}

export async function stopSubscription(): Promise<void> {
  await invoke("cmd_sysmon_stop_subscription");
}

export async function isSubscribing(): Promise<boolean> {
  return await invoke("cmd_sysmon_is_subscribing");
}

export async function getLogMaxSize(): Promise<number> {
  return await invoke<number>("cmd_sysmon_get_log_max_size");
}

export async function setLogMaxSize(sizeMb: number): Promise<void> {
  await invoke("cmd_sysmon_set_log_max_size", { sizeMb });
}

// --- P5 Monitor API ---
export async function monitorGetConfig(): Promise<MonitorConfig> {
  return await invoke<MonitorConfig>("cmd_monitor_get_config");
}

export async function monitorUpdateConfig(config: MonitorConfig): Promise<void> {
  await invoke("cmd_monitor_update_config", { config });
}

export async function monitorEnterBackground(): Promise<void> {
  await invoke("cmd_monitor_enter_background");
}

export async function monitorExitBackground(): Promise<void> {
  await invoke("cmd_monitor_exit_background");
}

export async function monitorGetAlerts(limit: number): Promise<Alert[]> {
  return await invoke<Alert[]>("cmd_monitor_get_alerts", { limit });
}

export async function monitorIsBackground(): Promise<boolean> {
  return await invoke<boolean>("cmd_monitor_is_background");
}

export async function monitorGetEvents(limit: number): Promise<MonitorEvent[]> {
  return await invoke<MonitorEvent[]>("cmd_monitor_get_events", { limit });
}

export async function monitorGetEventCount(): Promise<number> {
  return await invoke<number>("cmd_monitor_get_event_count");
}

export async function monitorSearchEvents(
  source?: string,
  event_type?: string,
  process_name?: string,
  key_field?: string,
  search_text?: string,
  limit: number = 1000,
  offset: number = 0,
): Promise<MonitorEvent[]> {
  return await invoke<MonitorEvent[]>("cmd_monitor_search_events", {
    source: source ?? null,
    eventType: event_type ?? null,
    processName: process_name ?? null,
    keyField: key_field ?? null,
    searchText: search_text ?? null,
    limit,
    offset,
  });
}

export async function searchEventPage(params: {
  source?: string | null;
  event_type?: string | null;
  process_name?: string | null;
  key_field?: string | null;
  is_external?: boolean | null;
  search_text?: string | null;
  limit?: number;
  offset?: number;
}): Promise<EventPage> {
  return await invoke<EventPage>("cmd_monitor_search_event_page", {
    query: {
      source: params.source ?? null,
      event_type: params.event_type ?? null,
      process_name: params.process_name ?? null,
      key_field: params.key_field ?? null,
      is_external: params.is_external ?? null,
      search_text: params.search_text ?? null,
      limit: params.limit ?? 200,
      offset: params.offset ?? 0,
    },
  });
}

export type { MonitorEvent };
export type { MonitorConfig, MonitorRule, NotifyAction, Alert };
